networks:
    dev:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "88:88"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - server_askue
            - frontend_askue
        networks:
            - dev

    frontend_askue:
        build:
            context: ./client
        networks:
            - dev
        env_file:
            - ./client/.env

    server_askue:
        build:
            context: ./server
        networks:
            - dev
        env_file:
            - ./server/.env
