import { leftMenuAdminReducer, leftMenuAdminSlice, setShow } from "./admin";
import {
    formHouseReducer,
    formHouseSlice,
    setActive,
    setFormHouse,
} from "./formHouse";
import {
    addObject,
    addSections,
    createObjects,
    createSections,
    getAllObjects,
    getAllSections,
    objectReducer,
    objectSlice,
    removeObject,
    sectionsReducer,
    sectionsSlice,
    setObject,
    setSections,
} from "./objectBuild";

import {
    check,
    getUser,
    loginIn,
    setIsAuth,
    setUser,
    userReducer,
    userSlice,
} from "./user";

import {
    deviceReducer,
    deviceSlice,
    getAllChannel,
    getAllKdl,
} from "./devices";

import {
    addElectricalMeters,
    createTestElectricalMeter,
    getAllElectricalMeterWithoutParameters,
    getAllElectricalMeters,
    getElectricalMetersByNumberFlat,
    getOneElectricalMeter,
    getTotalElectricalCount,
    setCurrentElectricalPage,
    setElectricalMeters,
    setLastElectricalMeters,
    setTotalElectricalCount,
    testElectricalMeterReducer,
    testElectricalMeterSlice,
} from "./testMeterElectrical";

import {
    addHeatMeters,
    createTestHeatMeter,
    getAllHeatMeter,
    getHeatMetersByNumberFlat,
    getOneHeatMeter,
    setCurrentHeatPage,
    setHeatMeters,
    setLastHeatMeters,
    setTotalHeatCount,
    testHeatMeterReducer,
    testHeatMeterSlice,
} from "./testMeterHeat";

import {
    addWaterMeters,
    createTestWaterMeter,
    getAllWaterMetersByUserAndObject,
    getOneWaterMeter,
    getWaterLimitAndCurrentPage,
    getWaterMetersByNumberFlat,
    setCurrentWaterPage,
    setLastWaterMeters,
    setTotalWaterCount,
    setWaterMeters,
    testWaterMeterReducer,
    testWaterMeterSlice,
} from "./testMeterWater";

import {
    addCoolBolid,
    coolWaterBildReducer,
    coolWaterBildSlice,
    removeCoolBolid,
} from "./bolid";

export {
    addCoolBolid,
    addElectricalMeters,
    addHeatMeters,
    addObject,
    addSections,
    addWaterMeters,
    check,
    coolWaterBildReducer,
    coolWaterBildSlice,
    createObjects,
    createSections,
    createTestElectricalMeter,
    createTestHeatMeter,
    createTestWaterMeter,
    deviceReducer,
    deviceSlice,
    formHouseReducer,
    formHouseSlice,
    getAllChannel,
    getAllElectricalMeterWithoutParameters,
    getAllElectricalMeters,
    getAllHeatMeter,
    getAllKdl,
    getAllObjects,
    getAllSections,
    getAllWaterMetersByUserAndObject,
    getElectricalMetersByNumberFlat,
    getHeatMetersByNumberFlat,
    getOneElectricalMeter,
    getOneHeatMeter,
    getOneWaterMeter,
    getTotalElectricalCount,
    getUser,
    getWaterLimitAndCurrentPage,
    getWaterMetersByNumberFlat,
    leftMenuAdminReducer,
    leftMenuAdminSlice,
    loginIn,
    objectReducer,
    objectSlice,
    removeCoolBolid,
    removeObject,
    sectionsReducer,
    sectionsSlice,
    setActive,
    setCurrentElectricalPage,
    setCurrentHeatPage,
    setCurrentWaterPage,
    setElectricalMeters,
    setFormHouse,
    setHeatMeters,
    setIsAuth,
    setLastElectricalMeters,
    setLastHeatMeters,
    setLastWaterMeters,
    setObject,
    setSections,
    setShow,
    setTotalElectricalCount,
    setTotalHeatCount,
    setTotalWaterCount,
    setUser,
    setWaterMeters,
    testElectricalMeterReducer,
    testElectricalMeterSlice,
    testHeatMeterReducer,
    testHeatMeterSlice,
    testWaterMeterReducer,
    testWaterMeterSlice,
    userReducer,
    userSlice,
};
