import {
    addMeters,
    createTestElectricalMeter,
    getAllElectricalMeters,
    getAllMeterWithoutParameters,
    getMetersByNumberFlat,
    getOneElectricalMeter,
    getTotalCount,
    setCurrentPage,
    setLastMeters,
    setMeters,
    setTotalCount,
    testElectricalMeterReducer,
    testElectricalMeterSlice,
} from "../testMeterElectrical/testElectricalMeterSlice";

export {
    addMeters as addElectricalMeters,
    createTestElectricalMeter,
    getAllMeterWithoutParameters as getAllElectricalMeterWithoutParameters,
    getAllElectricalMeters,
    getMetersByNumberFlat as getElectricalMetersByNumberFlat,
    getOneElectricalMeter,
    getTotalCount as getTotalElectricalCount,
    setCurrentPage as setCurrentElectricalPage,
    setMeters as setElectricalMeters,
    setLastMeters as setLastElectricalMeters,
    setTotalCount as setTotalElectricalCount,
    testElectricalMeterReducer,
    testElectricalMeterSlice,
};
