@hostHome = http://192.168.1.14:3333/api
@hostJob = http://192.168.3.16:7777/api
###
@host = {{hostJob}}
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJsb2dpbiI6ImFkbWluIiwicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTAxVDA4OjQyOjE3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTAxVDA4OjQyOjE3LjAwMFoiLCJVc2Vyc1JvbGUiOnsiaWQiOjEsInVzZXJJZCI6Miwicm9sZUlkIjoxLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTAxVDA5OjA1OjUyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTAxVDA5OjA1OjUyLjAwMFoifX1dLCJpYXQiOjE2OTM4OTkyMDAsImV4cCI6MTY5MzkyODAwMH0.X6Pn4aduWCbjVqXklewd5OOaalXlWJ9yw18opujWZds


### Roles
### Create Role
POST {{host}}/role HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "name": "admin"
}
### 
POST {{host}}/role HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "name": "user"
}

### Получить все
GET {{host}}/role HTTP/1.1
Content-Type: application/json; charset=utf-8

### Получить один
GET {{host}}/role/1 HTTP/1.1
Content-Type: application/json; charset=utf-8

### Auth
### Registration
POST {{host}}/auth/registration HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "login": "admin",
    "password": "admin",
    "role": "admin"
}

### Login
POST {{host}}/user/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "login": "admin",
    "password": "852046"
}
### ------------------ Объекты-----------------------------------------
### Получить все объекты
GET {{host}}/object HTTP/1.1
Authorization: Bearer {{token}}

###



### ----------------------- Вода Основная таблица ----------------------------
### Получим все счётчики
GET {{host}}/testAddWater/?objectId=9&limit=9&page=1 HTTP/1.1

### Создаём счётчики
POST {{host}}/testAddWater HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "section": 1,
    "floor": 1,
    "flat": 0,
    "office": 2,
    "numberKdl": 1,
    "channelCool": 1,
    "channelHot": 2,
    "numberMeterCool": 12,
    "numberMeterHot": 122,
    "sumMeterCool": 1,
    "sumMeterHot": 1,
    "userId": 1,
    "objectBuildId": 9
}
###

### Получим линии
GET {{host}}/testAddHeat/line/?objectBuildId=8 HTTP/1.1

###





### ----------------------- Пульсар вода ----------------------------
### Получим все номера счётчиков импульсов
GET {{host}}/pulsarWater/?objectBuildId=8 HTTP/1.1

###

### Получим все счётчики
GET {{host}}/pulsarWater/getByNumber/?numberKdl=9603534 HTTP/1.1

###